import type { RuntimeGameplayDebugPanelDescriptor } from './runtime-gameplay-debug-panels';

export const runtimeGameplayDebugPanelDescriptors: RuntimeGameplayDebugPanelDescriptor[] = [
  // Phase-specific gameplay debug panels are generated by gameplay-builder.
  // Register descriptors here; keep concrete gameplay panels out of the template baseline.
];
